name: Build and Deploy Stage front

on:
  push:
    branches:
      - Dev
      - Stage
      - Prod

jobs:
  build:
    runs-on: [self-hosted, Linux, X64]

    steps:
      - uses: actions/checkout@v3
      
      - uses: docker/setup-buildx-action@v2    

      - name: Local server Deployment
        run: |
          cd /home/sadman-sajid/firstapp/frontend  # local project directory
          git fetch --all
          git checkout ${{ github.ref_name }}
          docker compose down
          docker compose build
          docker compose up -d